In [1]:
import pandas as pd

In [17]:
data = {"Name": ["Spongebob","Patrick","Squidward"],
        "Age":[30,35,50]}

In [18]:
df = pd.DataFrame(data)
df

        Name  Age
0  Spongebob   30
1    Patrick   35
2  Squidward   50

In [19]:
df = pd.DataFrame(data, index= ["Employee1","Employee2","Employee3"])
df

                Name  Age
Employee1  Spongebob   30
Employee2    Patrick   35
Employee3  Squidward   50

In [20]:
df.loc["Employee1"]

Name    Spongebob
Age            30
Name: Employee1, dtype: object

In [21]:
df.iloc[2]

Name    Squidward
Age            50
Name: Employee3, dtype: object

In [22]:
# Add a new column
df["Job"] = ["Cook","N/A","Cashier"]
df

                Name  Age      Job
Employee1  Spongebob   30     Cook
Employee2    Patrick   35      N/A
Employee3  Squidward   50  Cashier

In [23]:
# Add a new row
new_row = pd.DataFrame([{"Name":"Sandy","Age":28,"Job":"Engineer"}],
                       index=["Employee4"])
df = pd.concat([df, new_row])
df

                Name  Age       Job
Employee1  Spongebob   30      Cook
Employee2    Patrick   35       N/A
Employee3  Squidward   50   Cashier
Employee4      Sandy   28  Engineer

In [25]:
# Add new rows
new_rows = pd.DataFrame([{"Name":"Eugene","Age":60,"Job":"Manager"},
                        {"Name":"Harry","Age":29,"Job":"Assistant"}],
                       index=["Employee5","Employee6"])
df = pd.concat([df, new_rows])
df

                Name  Age        Job
Employee1  Spongebob   30       Cook
Employee2    Patrick   35        N/A
Employee3  Squidward   50    Cashier
Employee4      Sandy   28   Engineer
Employee5     Eugene   60    Manager
Employee6      Harry   29  Assistant