In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

In [5]:
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire       NaN     0.6     8.5          0
4      5  Charmeleon      Fire       NaN     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water       NaN     0.5     9.0          0
7      8   Wartortle     Water       NaN     1.0    22.5          0
8      9   Blastoise     Water       NaN     1.6    85.5          0
9     10    Caterpie       Bug       NaN     0.3     2.9          0
10    11     Metapod       Bug       NaN     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal       NaN     0.3     3.5          0
19    20    Raticate    Normal       NaN     0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison       NaN     2.0     6.9          0
23    24       Arbok    Poison       NaN     3.5    65.0          0
24    25     Pikachu  Electric       NaN     0.4     6.0          0
25    26      Raichu  Electric       NaN     0.8    30.0          0
26    27   Sandshrew    Ground       NaN     0.6    12.0          0
27    28   Sandslash    Ground       NaN     1.0    29.5          0
28    29    Nidoran♀    Poison       NaN     0.4     7.0          0
29    30    Nidorina    Poison       NaN     0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison       NaN     0.5     9.0          0
32    33    Nidorino    Poison       NaN     0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy       NaN     0.6     7.5          0
35    36    Clefable     Fairy       NaN     1.3    40.0          0
36    37      Vulpix      Fire       NaN     0.6     9.9          0
37    38   Ninetales      Fire       NaN     1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     Grass    Poison     0.5     5.4          0
43    44       Gloom     Grass    Poison     0.8     8.6          0
44    45   Vileplume     Grass    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground       NaN     0.2     0.8          0
50    51     Dugtrio    Ground       NaN     0.7    33.3          0
51    52      Meowth    Normal       NaN     0.4     4.2          0
52    53     Persian    Normal       NaN     1.0    32.0          0
53    54     Psyduck     Water       NaN     0.8    19.6          0
54    55     Golduck     Water       NaN     1.7    76.6          0
55    56      Mankey  Fighting       NaN     0.5    28.0          0
56    57    Primeape  Fighting       NaN     1.0    32.0          0
57    58   Growlithe      Fire       NaN     0.7    19.0          0
58    59    Arcanine      Fire       NaN     1.9   155.0          0
59    60     Poliwag     Water       NaN     0.6    12.4          0
60    61   Poliwhirl     Water       NaN     1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic       NaN     0.9    19.5          0
63    64     Kadabra   Psychic       NaN     1.3    56.5          0
64    65    Alakazam   Psychic       NaN     1.5    48.0          0
65    66      Machop  Fighting       NaN     0.8    19.5          0
66    67     Machoke  Fighting       NaN     1.5    70.5          0
67    68     Machamp  Fighting       NaN     1.6   130.0          0
68    69  Bellsprout     Grass    Poison     0.7     4.0          0
69    70  Weepinbell     Grass    Poison     1.0     6.4          0
70    71  Victreebel     Grass    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire       NaN     1.0    30.0          0
77    78    Rapidash      Fire       NaN     1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water       NaN     1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison       NaN     0.9    30.0          0
88    89         Muk    Poison       NaN     1.2    30.0          0
89    90    Shellder     Water       NaN     0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic       NaN     1.0    32.4          0
96    97       Hypno   Psychic       NaN     1.6    75.6          0
97    98      Krabby     Water       NaN     0.4     6.5          0
98    99     Kingler     Water       NaN     1.3    60.0          0
99   100     Voltorb  Electric       NaN     0.5    10.4          0
100  101   Electrode  Electric       NaN     1.2    66.6          0
101  102   Exeggcute     Grass   Psychic     0.4     2.5          0
102  103   Exeggutor     Grass   Psychic     2.0   120.0          0
103  104      Cubone    Ground       NaN     0.4     6.5          0
104  105     Marowak    Ground       NaN     1.0    45.0          0
105  106   Hitmonlee  Fighting       NaN     1.5    49.8          0
106  107  Hitmonchan  Fighting       NaN     1.4    50.2          0
107  108   Lickitung    Normal       NaN     1.2    65.5          0
108  109     Koffing    Poison       NaN     0.6     1.0          0
109  110     Weezing    Poison       NaN     1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal       NaN     1.1    34.6          0
113  114     Tangela     Grass       NaN     1.0    35.0          0
114  115  Kangaskhan    Normal       NaN     2.2    80.0          0
115  116      Horsea     Water       NaN     0.4     8.0          0
116  117      Seadra     Water       NaN     1.2    25.0          0
117  118     Goldeen     Water       NaN     0.6    15.0          0
118  119     Seaking     Water       NaN     1.3    39.0          0
119  120      Staryu     Water       NaN     0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric       NaN     1.1    30.0          0
125  126      Magmar      Fire       NaN     1.3    44.5          0
126  127      Pinsir       Bug       NaN     1.5    55.0          0
127  128      Tauros    Normal       NaN     1.4    88.4          0
128  129    Magikarp     Water       NaN     0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal       NaN     0.3     4.0          0
132  133       Eevee    Normal       NaN     0.3     6.5          0
133  134    Vaporeon     Water       NaN     1.0    29.0          0
134  135     Jolteon  Electric       NaN     0.8    24.5          0
135  136     Flareon      Fire       NaN     0.9    25.0          0
136  137     Porygon    Normal       NaN     0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal       NaN     2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon       NaN     1.8     3.3          0
147  148   Dragonair    Dragon       NaN     4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic       NaN     2.0   122.0          1

In [6]:
df = pd.read_json("data.json")
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire             0.6     8.5          0
4      5  Charmeleon     Fire             1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon             1.8     3.3          0
147  148   Dragonair   Dragon             4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic             2.0   122.0          1

[150 rows x 7 columns]

In [7]:
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire               0.6     8.5          0
4      5  Charmeleon      Fire               1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water               0.5     9.0          0
7      8   Wartortle     Water               1.0    22.5          0
8      9   Blastoise     Water               1.6    85.5          0
9     10    Caterpie       Bug               0.3     2.9          0
10    11     Metapod       Bug               0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal               0.3     3.5          0
19    20    Raticate    Normal               0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison               2.0     6.9          0
23    24       Arbok    Poison               3.5    65.0          0
24    25     Pikachu  Electric               0.4     6.0          0
25    26      Raichu  Electric               0.8    30.0          0
26    27   Sandshrew    Ground               0.6    12.0          0
27    28   Sandslash    Ground               1.0    29.5          0
28    29    Nidoran♀    Poison               0.4     7.0          0
29    30    Nidorina    Poison               0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison               0.5     9.0          0
32    33    Nidorino    Poison               0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy               0.6     7.5          0
35    36    Clefable     Fairy               1.3    40.0          0
36    37      Vulpix      Fire               0.6     9.9          0
37    38   Ninetales      Fire               1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     Grass    Poison     0.5     5.4          0
43    44       Gloom     Grass    Poison     0.8     8.6          0
44    45   Vileplume     Grass    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground               0.2     0.8          0
50    51     Dugtrio    Ground               0.7    33.3          0
51    52      Meowth    Normal               0.4     4.2          0
52    53     Persian    Normal               1.0    32.0          0
53    54     Psyduck     Water               0.8    19.6          0
54    55     Golduck     Water               1.7    76.6          0
55    56      Mankey  Fighting               0.5    28.0          0
56    57    Primeape  Fighting               1.0    32.0          0
57    58   Growlithe      Fire               0.7    19.0          0
58    59    Arcanine      Fire               1.9   155.0          0
59    60     Poliwag     Water               0.6    12.4          0
60    61   Poliwhirl     Water               1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic               0.9    19.5          0
63    64     Kadabra   Psychic               1.3    56.5          0
64    65    Alakazam   Psychic               1.5    48.0          0
65    66      Machop  Fighting               0.8    19.5          0
66    67     Machoke  Fighting               1.5    70.5          0
67    68     Machamp  Fighting               1.6   130.0          0
68    69  Bellsprout     Grass    Poison     0.7     4.0          0
69    70  Weepinbell     Grass    Poison     1.0     6.4          0
70    71  Victreebel     Grass    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire               1.0    30.0          0
77    78    Rapidash      Fire               1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water               1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison               0.9    30.0          0
88    89         Muk    Poison               1.2    30.0          0
89    90    Shellder     Water               0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic               1.0    32.4          0
96    97       Hypno   Psychic               1.6    75.6          0
97    98      Krabby     Water               0.4     6.5          0
98    99     Kingler     Water               1.3    60.0          0
99   100     Voltorb  Electric               0.5    10.4          0
100  101   Electrode  Electric               1.2    66.6          0
101  102   Exeggcute     Grass   Psychic     0.4     2.5          0
102  103   Exeggutor     Grass   Psychic     2.0   120.0          0
103  104      Cubone    Ground               0.4     6.5          0
104  105     Marowak    Ground               1.0    45.0          0
105  106   Hitmonlee  Fighting               1.5    49.8          0
106  107  Hitmonchan  Fighting               1.4    50.2          0
107  108   Lickitung    Normal               1.2    65.5          0
108  109     Koffing    Poison               0.6     1.0          0
109  110     Weezing    Poison               1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal               1.1    34.6          0
113  114     Tangela     Grass               1.0    35.0          0
114  115  Kangaskhan    Normal               2.2    80.0          0
115  116      Horsea     Water               0.4     8.0          0
116  117      Seadra     Water               1.2    25.0          0
117  118     Goldeen     Water               0.6    15.0          0
118  119     Seaking     Water               1.3    39.0          0
119  120      Staryu     Water               0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric               1.1    30.0          0
125  126      Magmar      Fire               1.3    44.5          0
126  127      Pinsir       Bug               1.5    55.0          0
127  128      Tauros    Normal               1.4    88.4          0
128  129    Magikarp     Water               0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal               0.3     4.0          0
132  133       Eevee    Normal               0.3     6.5          0
133  134    Vaporeon     Water               1.0    29.0          0
134  135     Jolteon  Electric               0.8    24.5          0
135  136     Flareon      Fire               0.9    25.0          0
136  137     Porygon    Normal               0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal               2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon               1.8     3.3          0
147  148   Dragonair    Dragon               4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic               2.0   122.0          1