In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
# selection by column
df["Name"]

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
145       Moltres
146       Dratini
147     Dragonair
148     Dragonite
149        Mewtwo
Name: Name, Length: 150, dtype: str

In [5]:
print(df["Name"].to_string())

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
5       Charizard
6        Squirtle
7       Wartortle
8       Blastoise
9        Caterpie
10        Metapod
11     Butterfree
12         Weedle
13         Kakuna
14       Beedrill
15         Pidgey
16      Pidgeotto
17        Pidgeot
18        Rattata
19       Raticate
20        Spearow
21         Fearow
22          Ekans
23          Arbok
24        Pikachu
25         Raichu
26      Sandshrew
27      Sandslash
28       Nidoran♀
29       Nidorina
30      Nidoqueen
31       Nidoran♂
32       Nidorino
33       Nidoking
34       Clefairy
35       Clefable
36         Vulpix
37      Ninetales
38     Jigglypuff
39     Wigglytuff
40          Zubat
41         Golbat
42         Oddish
43          Gloom
44      Vileplume
45          Paras
46       Parasect
47        Venonat
48       Venomoth
49        Diglett
50        Dugtrio
51         Meowth
52        Persian
53        Psyduck
54        Golduck
55         Mankey
56       Primeape
57      Growlithe
58       Arcanine
59        Poliwag
60      Poliwhirl
61      Poliwrath
62           Abra
63        Kadabra
64       Alakazam
65         Machop
66        Machoke
67        Machamp
68     Bellsprout
69     Weepinbell
70     Victreebel
71      Tentacool
72     Tentacruel
73        Geodude
74       Graveler
75          Golem
76         Ponyta
77       Rapidash
78       Slowpoke
79        Slowbro
80      Magnemite
81       Magneton
82     Farfetch'd
83          Doduo
84         Dodrio
85           Seel
86        Dewgong
87         Grimer
88            Muk
89       Shellder
90       Cloyster
91         Gastly
92        Haunter
93         Gengar
94           Onix
95        Drowzee
96          Hypno
97         Krabby
98        Kingler
99        Voltorb
100     Electrode
101     Exeggcute
102     Exeggutor
103        Cubone
104       Marowak
105     Hitmonlee
106    Hitmonchan
107     Lickitung
108       Koffing
109       Weezing
110       Rhyhorn
111        Rhydon
112       Chansey
113       Tangela
114    Kangaskhan
115        Horsea
116        Seadra
117       Goldeen
118       Seaking
119        Staryu
120       Starmie
121      Mr. Mime
122       Scyther
123          Jynx
124    Electabuzz
125        Magmar
126        Pinsir
127        Tauros
128      Magikarp
129      Gyarados
130        Lapras
131         Ditto
132         Eevee
133      Vaporeon
134       Jolteon
135       Flareon
136       Porygon
137       Omanyte
138       Omastar
139        Kabuto
140      Kabutops
141    Aerodactyl
142       Snorlax
143      Articuno
144        Zapdos
145       Moltres
146       Dratini
147     Dragonair
148     Dragonite
149        Mewtwo

In [6]:
print(df["Height"].to_string())

0      0.7
1      1.0
2      2.0
3      0.6
4      1.1
5      1.7
6      0.5
7      1.0
8      1.6
9      0.3
10     0.7
11     1.1
12     0.3
13     0.6
14     1.0
15     0.3
16     1.1
17     1.5
18     0.3
19     0.7
20     0.3
21     1.2
22     2.0
23     3.5
24     0.4
25     0.8
26     0.6
27     1.0
28     0.4
29     0.8
30     1.3
31     0.5
32     0.9
33     1.4
34     0.6
35     1.3
36     0.6
37     1.1
38     0.5
39     1.0
40     0.8
41     1.6
42     0.5
43     0.8
44     1.2
45     0.3
46     1.0
47     1.0
48     1.5
49     0.2
50     0.7
51     0.4
52     1.0
53     0.8
54     1.7
55     0.5
56     1.0
57     0.7
58     1.9
59     0.6
60     1.0
61     1.3
62     0.9
63     1.3
64     1.5
65     0.8
66     1.5
67     1.6
68     0.7
69     1.0
70     1.7
71     0.9
72     1.6
73     0.4
74     1.0
75     1.4
76     1.0
77     1.7
78     1.2
79     1.6
80     0.3
81     1.0
82     0.8
83     1.4
84     1.8
85     1.1
86     1.7
87     0.9
88     1.2
89     0.3
90     1.5
91     1.3
92     1.6
93     1.5
94     8.8
95     1.0
96     1.6
97     0.4
98     1.3
99     0.5
100    1.2
101    0.4
102    2.0
103    0.4
104    1.0
105    1.5
106    1.4
107    1.2
108    0.6
109    1.2
110    1.0
111    1.9
112    1.1
113    1.0
114    2.2
115    0.4
116    1.2
117    0.6
118    1.3
119    0.8
120    1.1
121    1.3
122    1.5
123    1.4
124    1.1
125    1.3
126    1.5
127    1.4
128    0.9
129    6.5
130    2.5
131    0.3
132    0.3
133    1.0
134    0.8
135    0.9
136    0.8
137    0.4
138    1.0
139    0.5
140    1.3
141    1.8
142    2.1
143    1.7
144    1.6
145    2.0
146    1.8
147    4.0
148    2.2
149    2.0

In [10]:
df[["Name","Height","Weight"]]

           Name  Height  Weight
0     Bulbasaur     0.7     6.9
1       Ivysaur     1.0    13.0
2      Venusaur     2.0   100.0
3    Charmander     0.6     8.5
4    Charmeleon     1.1    19.0
..          ...     ...     ...
145     Moltres     2.0    60.0
146     Dratini     1.8     3.3
147   Dragonair     4.0    16.5
148   Dragonite     2.2   210.0
149      Mewtwo     2.0   122.0

[150 rows x 3 columns]

In [11]:
print(df[["Name","Height","Weight"]].to_string())

           Name  Height  Weight
0     Bulbasaur     0.7     6.9
1       Ivysaur     1.0    13.0
2      Venusaur     2.0   100.0
3    Charmander     0.6     8.5
4    Charmeleon     1.1    19.0
5     Charizard     1.7    90.5
6      Squirtle     0.5     9.0
7     Wartortle     1.0    22.5
8     Blastoise     1.6    85.5
9      Caterpie     0.3     2.9
10      Metapod     0.7     9.9
11   Butterfree     1.1    32.0
12       Weedle     0.3     3.2
13       Kakuna     0.6    10.0
14     Beedrill     1.0    29.5
15       Pidgey     0.3     1.8
16    Pidgeotto     1.1    30.0
17      Pidgeot     1.5    39.5
18      Rattata     0.3     3.5
19     Raticate     0.7    18.5
20      Spearow     0.3     2.0
21       Fearow     1.2    38.0
22        Ekans     2.0     6.9
23        Arbok     3.5    65.0
24      Pikachu     0.4     6.0
25       Raichu     0.8    30.0
26    Sandshrew     0.6    12.0
27    Sandslash     1.0    29.5
28     Nidoran♀     0.4     7.0
29     Nidorina     0.8    20.0
30    Nidoqueen     1.3    60.0
31     Nidoran♂     0.5     9.0
32     Nidorino     0.9    19.5
33     Nidoking     1.4    62.0
34     Clefairy     0.6     7.5
35     Clefable     1.3    40.0
36       Vulpix     0.6     9.9
37    Ninetales     1.1    19.9
38   Jigglypuff     0.5     5.5
39   Wigglytuff     1.0    12.0
40        Zubat     0.8     7.5
41       Golbat     1.6    55.0
42       Oddish     0.5     5.4
43        Gloom     0.8     8.6
44    Vileplume     1.2    18.6
45        Paras     0.3     5.4
46     Parasect     1.0    29.5
47      Venonat     1.0    30.0
48     Venomoth     1.5    12.5
49      Diglett     0.2     0.8
50      Dugtrio     0.7    33.3
51       Meowth     0.4     4.2
52      Persian     1.0    32.0
53      Psyduck     0.8    19.6
54      Golduck     1.7    76.6
55       Mankey     0.5    28.0
56     Primeape     1.0    32.0
57    Growlithe     0.7    19.0
58     Arcanine     1.9   155.0
59      Poliwag     0.6    12.4
60    Poliwhirl     1.0    20.0
61    Poliwrath     1.3    54.0
62         Abra     0.9    19.5
63      Kadabra     1.3    56.5
64     Alakazam     1.5    48.0
65       Machop     0.8    19.5
66      Machoke     1.5    70.5
67      Machamp     1.6   130.0
68   Bellsprout     0.7     4.0
69   Weepinbell     1.0     6.4
70   Victreebel     1.7    15.5
71    Tentacool     0.9    45.5
72   Tentacruel     1.6    55.0
73      Geodude     0.4    20.0
74     Graveler     1.0   105.0
75        Golem     1.4   300.0
76       Ponyta     1.0    30.0
77     Rapidash     1.7    95.0
78     Slowpoke     1.2    36.0
79      Slowbro     1.6    78.5
80    Magnemite     0.3     6.0
81     Magneton     1.0    60.0
82   Farfetch'd     0.8    15.0
83        Doduo     1.4    39.2
84       Dodrio     1.8    85.2
85         Seel     1.1    90.0
86      Dewgong     1.7   120.0
87       Grimer     0.9    30.0
88          Muk     1.2    30.0
89     Shellder     0.3     4.0
90     Cloyster     1.5   132.5
91       Gastly     1.3     0.1
92      Haunter     1.6     0.1
93       Gengar     1.5    40.5
94         Onix     8.8   210.0
95      Drowzee     1.0    32.4
96        Hypno     1.6    75.6
97       Krabby     0.4     6.5
98      Kingler     1.3    60.0
99      Voltorb     0.5    10.4
100   Electrode     1.2    66.6
101   Exeggcute     0.4     2.5
102   Exeggutor     2.0   120.0
103      Cubone     0.4     6.5
104     Marowak     1.0    45.0
105   Hitmonlee     1.5    49.8
106  Hitmonchan     1.4    50.2
107   Lickitung     1.2    65.5
108     Koffing     0.6     1.0
109     Weezing     1.2     9.5
110     Rhyhorn     1.0   115.0
111      Rhydon     1.9   120.0
112     Chansey     1.1    34.6
113     Tangela     1.0    35.0
114  Kangaskhan     2.2    80.0
115      Horsea     0.4     8.0
116      Seadra     1.2    25.0
117     Goldeen     0.6    15.0
118     Seaking     1.3    39.0
119      Staryu     0.8    34.5
120     Starmie     1.1    80.0
121    Mr. Mime     1.3    54.5
122     Scyther     1.5    56.0
123        Jynx     1.4    40.6
124  Electabuzz     1.1    30.0
125      Magmar     1.3    44.5
126      Pinsir     1.5    55.0
127      Tauros     1.4    88.4
128    Magikarp     0.9    10.0
129    Gyarados     6.5   235.0
130      Lapras     2.5   220.0
131       Ditto     0.3     4.0
132       Eevee     0.3     6.5
133    Vaporeon     1.0    29.0
134     Jolteon     0.8    24.5
135     Flareon     0.9    25.0
136     Porygon     0.8    36.5
137     Omanyte     0.4     7.5
138     Omastar     1.0    35.0
139      Kabuto     0.5    11.5
140    Kabutops     1.3    40.5
141  Aerodactyl     1.8    59.0
142     Snorlax     2.1   460.0
143    Articuno     1.7    55.4
144      Zapdos     1.6    52.6
145     Moltres     2.0    60.0
146     Dratini     1.8     3.3
147   Dragonair     4.0    16.5
148   Dragonite     2.2   210.0
149      Mewtwo     2.0   122.0

# Selection By Rows

In [12]:
print(df.loc[0])

No                   1
Name         Bulbasaur
Type1            Grass
Type2           Poison
Height             0.7
Weight             6.9
Legendary            0
Name: 0, dtype: object

In [13]:
df = pd.read_csv("data.csv",index_col="Name")
df

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [15]:
print(df.loc["Pikachu"])

No                 25
Type1        Electric
Type2             NaN
Height            0.4
Weight            6.0
Legendary           0
Name: Pikachu, dtype: object

In [17]:
print(df.loc["Pikachu",["Height","Weight"]])

Height    0.4
Weight    6.0
Name: Pikachu, dtype: float64

In [19]:
print(df.loc["Charizard",["Height","Weight"]])

Height     1.7
Weight    90.5
Name: Charizard, dtype: float64

In [20]:
print(df.loc["Charizard":"Blastoise",["Height","Weight"]])

           Height  Weight
Name
Charizard     1.7    90.5
Squirtle      0.5     9.0
Wartortle     1.0    22.5
Blastoise     1.6    85.5

In [21]:
print(df.iloc[0:11])

            No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Ivysaur      2  Grass  Poison     1.0    13.0          0
Venusaur     3  Grass  Poison     2.0   100.0          0
Charmander   4   Fire     NaN     0.6     8.5          0
Charmeleon   5   Fire     NaN     1.1    19.0          0
Charizard    6   Fire  Flying     1.7    90.5          0
Squirtle     7  Water     NaN     0.5     9.0          0
Wartortle    8  Water     NaN     1.0    22.5          0
Blastoise    9  Water     NaN     1.6    85.5          0
Caterpie    10    Bug     NaN     0.3     2.9          0
Metapod     11    Bug     NaN     0.7     9.9          0

In [22]:
print(df.iloc[0:11:2])

            No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1  Grass  Poison     0.7     6.9          0
Venusaur     3  Grass  Poison     2.0   100.0          0
Charmeleon   5   Fire     NaN     1.1    19.0          0
Squirtle     7  Water     NaN     0.5     9.0          0
Blastoise    9  Water     NaN     1.6    85.5          0
Metapod     11    Bug     NaN     0.7     9.9          0

In [23]:
print(df.iloc[0:11:2, 0:3])

            No  Type1   Type2
Name
Bulbasaur    1  Grass  Poison
Venusaur     3  Grass  Poison
Charmeleon   5   Fire     NaN
Squirtle     7  Water     NaN
Blastoise    9  Water     NaN
Metapod     11    Bug     NaN

Excercise

In [26]:
pokemon = input("Enter a name of pokemon:")
try:
    print(df.loc[pokemon])
except KeyError as e:
    print(f"{pokemon} not found")

Enter a name of pokemon: 51

51 not found