In [7]:
import pandas as pd

Data Cleaning = The process of fixing/ removing incomplete, incorrect, or irrelevant data.
                75% of work done with pandas is data cleaning.

In [8]:
df = pd.read_csv("data.csv")
df.head(5)

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0

In [10]:
# droping irrelevant column
df = df.drop(columns=["Legendary","No"])
df.head(5)

         Name  Type1   Type2  Height  Weight
0   Bulbasaur  Grass  Poison     0.7     6.9
1     Ivysaur  Grass  Poison     1.0    13.0
2    Venusaur  Grass  Poison     2.0   100.0
3  Charmander   Fire     NaN     0.6     8.5
4  Charmeleon   Fire     NaN     1.1    19.0

In [14]:
# handling missing value
df = df.dropna(subset=["Type2"])
print(df.to_string())
print(df["Name"].count())

           Name     Type1     Type2  Height  Weight
0     Bulbasaur     Grass    Poison     0.7     6.9
1       Ivysaur     Grass    Poison     1.0    13.0
2      Venusaur     Grass    Poison     2.0   100.0
5     Charizard      Fire    Flying     1.7    90.5
11   Butterfree       Bug    Flying     1.1    32.0
12       Weedle       Bug    Poison     0.3     3.2
13       Kakuna       Bug    Poison     0.6    10.0
14     Beedrill       Bug    Poison     1.0    29.5
15       Pidgey    Normal    Flying     0.3     1.8
16    Pidgeotto    Normal    Flying     1.1    30.0
17      Pidgeot    Normal    Flying     1.5    39.5
20      Spearow    Normal    Flying     0.3     2.0
21       Fearow    Normal    Flying     1.2    38.0
30    Nidoqueen    Poison    Ground     1.3    60.0
33     Nidoking    Poison    Ground     1.4    62.0
38   Jigglypuff    Normal     Fairy     0.5     5.5
39   Wigglytuff    Normal     Fairy     1.0    12.0
40        Zubat    Poison    Flying     0.8     7.5
41       Golbat    Poison    Flying     1.6    55.0
42       Oddish     Grass    Poison     0.5     5.4
43        Gloom     Grass    Poison     0.8     8.6
44    Vileplume     Grass    Poison     1.2    18.6
45        Paras       Bug     Grass     0.3     5.4
46     Parasect       Bug     Grass     1.0    29.5
47      Venonat       Bug    Poison     1.0    30.0
48     Venomoth       Bug    Poison     1.5    12.5
61    Poliwrath     Water  Fighting     1.3    54.0
68   Bellsprout     Grass    Poison     0.7     4.0
69   Weepinbell     Grass    Poison     1.0     6.4
70   Victreebel     Grass    Poison     1.7    15.5
71    Tentacool     Water    Poison     0.9    45.5
72   Tentacruel     Water    Poison     1.6    55.0
73      Geodude      Rock    Ground     0.4    20.0
74     Graveler      Rock    Ground     1.0   105.0
75        Golem      Rock    Ground     1.4   300.0
78     Slowpoke     Water   Psychic     1.2    36.0
79      Slowbro     Water   Psychic     1.6    78.5
80    Magnemite  Electric     Steel     0.3     6.0
81     Magneton  Electric     Steel     1.0    60.0
82   Farfetch'd    Normal    Flying     0.8    15.0
83        Doduo    Normal    Flying     1.4    39.2
84       Dodrio    Normal    Flying     1.8    85.2
86      Dewgong     Water       Ice     1.7   120.0
90     Cloyster     Water       Ice     1.5   132.5
91       Gastly     Ghost    Poison     1.3     0.1
92      Haunter     Ghost    Poison     1.6     0.1
93       Gengar     Ghost    Poison     1.5    40.5
94         Onix      Rock    Ground     8.8   210.0
101   Exeggcute     Grass   Psychic     0.4     2.5
102   Exeggutor     Grass   Psychic     2.0   120.0
110     Rhyhorn    Ground      Rock     1.0   115.0
111      Rhydon    Ground      Rock     1.9   120.0
120     Starmie     Water   Psychic     1.1    80.0
121    Mr. Mime   Psychic     Fairy     1.3    54.5
122     Scyther       Bug    Flying     1.5    56.0
123        Jynx       Ice   Psychic     1.4    40.6
129    Gyarados     Water    Flying     6.5   235.0
130      Lapras     Water       Ice     2.5   220.0
137     Omanyte      Rock     Water     0.4     7.5
138     Omastar      Rock     Water     1.0    35.0
139      Kabuto      Rock     Water     0.5    11.5
140    Kabutops      Rock     Water     1.3    40.5
141  Aerodactyl      Rock    Flying     1.8    59.0
143    Articuno       Ice    Flying     1.7    55.4
144      Zapdos  Electric    Flying     1.6    52.6
145     Moltres      Fire    Flying     2.0    60.0
148   Dragonite    Dragon    Flying     2.2   210.0
67

In [15]:
df = pd.read_csv("data.csv")
df = df.fillna({"Type2":"Non"})
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire       Non     0.6     8.5          0
4      5  Charmeleon      Fire       Non     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water       Non     0.5     9.0          0
7      8   Wartortle     Water       Non     1.0    22.5          0
8      9   Blastoise     Water       Non     1.6    85.5          0
9     10    Caterpie       Bug       Non     0.3     2.9          0
10    11     Metapod       Bug       Non     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal       Non     0.3     3.5          0
19    20    Raticate    Normal       Non     0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison       Non     2.0     6.9          0
23    24       Arbok    Poison       Non     3.5    65.0          0
24    25     Pikachu  Electric       Non     0.4     6.0          0
25    26      Raichu  Electric       Non     0.8    30.0          0
26    27   Sandshrew    Ground       Non     0.6    12.0          0
27    28   Sandslash    Ground       Non     1.0    29.5          0
28    29    Nidoran♀    Poison       Non     0.4     7.0          0
29    30    Nidorina    Poison       Non     0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison       Non     0.5     9.0          0
32    33    Nidorino    Poison       Non     0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy       Non     0.6     7.5          0
35    36    Clefable     Fairy       Non     1.3    40.0          0
36    37      Vulpix      Fire       Non     0.6     9.9          0
37    38   Ninetales      Fire       Non     1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     Grass    Poison     0.5     5.4          0
43    44       Gloom     Grass    Poison     0.8     8.6          0
44    45   Vileplume     Grass    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground       Non     0.2     0.8          0
50    51     Dugtrio    Ground       Non     0.7    33.3          0
51    52      Meowth    Normal       Non     0.4     4.2          0
52    53     Persian    Normal       Non     1.0    32.0          0
53    54     Psyduck     Water       Non     0.8    19.6          0
54    55     Golduck     Water       Non     1.7    76.6          0
55    56      Mankey  Fighting       Non     0.5    28.0          0
56    57    Primeape  Fighting       Non     1.0    32.0          0
57    58   Growlithe      Fire       Non     0.7    19.0          0
58    59    Arcanine      Fire       Non     1.9   155.0          0
59    60     Poliwag     Water       Non     0.6    12.4          0
60    61   Poliwhirl     Water       Non     1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic       Non     0.9    19.5          0
63    64     Kadabra   Psychic       Non     1.3    56.5          0
64    65    Alakazam   Psychic       Non     1.5    48.0          0
65    66      Machop  Fighting       Non     0.8    19.5          0
66    67     Machoke  Fighting       Non     1.5    70.5          0
67    68     Machamp  Fighting       Non     1.6   130.0          0
68    69  Bellsprout     Grass    Poison     0.7     4.0          0
69    70  Weepinbell     Grass    Poison     1.0     6.4          0
70    71  Victreebel     Grass    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire       Non     1.0    30.0          0
77    78    Rapidash      Fire       Non     1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water       Non     1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison       Non     0.9    30.0          0
88    89         Muk    Poison       Non     1.2    30.0          0
89    90    Shellder     Water       Non     0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic       Non     1.0    32.4          0
96    97       Hypno   Psychic       Non     1.6    75.6          0
97    98      Krabby     Water       Non     0.4     6.5          0
98    99     Kingler     Water       Non     1.3    60.0          0
99   100     Voltorb  Electric       Non     0.5    10.4          0
100  101   Electrode  Electric       Non     1.2    66.6          0
101  102   Exeggcute     Grass   Psychic     0.4     2.5          0
102  103   Exeggutor     Grass   Psychic     2.0   120.0          0
103  104      Cubone    Ground       Non     0.4     6.5          0
104  105     Marowak    Ground       Non     1.0    45.0          0
105  106   Hitmonlee  Fighting       Non     1.5    49.8          0
106  107  Hitmonchan  Fighting       Non     1.4    50.2          0
107  108   Lickitung    Normal       Non     1.2    65.5          0
108  109     Koffing    Poison       Non     0.6     1.0          0
109  110     Weezing    Poison       Non     1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal       Non     1.1    34.6          0
113  114     Tangela     Grass       Non     1.0    35.0          0
114  115  Kangaskhan    Normal       Non     2.2    80.0          0
115  116      Horsea     Water       Non     0.4     8.0          0
116  117      Seadra     Water       Non     1.2    25.0          0
117  118     Goldeen     Water       Non     0.6    15.0          0
118  119     Seaking     Water       Non     1.3    39.0          0
119  120      Staryu     Water       Non     0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric       Non     1.1    30.0          0
125  126      Magmar      Fire       Non     1.3    44.5          0
126  127      Pinsir       Bug       Non     1.5    55.0          0
127  128      Tauros    Normal       Non     1.4    88.4          0
128  129    Magikarp     Water       Non     0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal       Non     0.3     4.0          0
132  133       Eevee    Normal       Non     0.3     6.5          0
133  134    Vaporeon     Water       Non     1.0    29.0          0
134  135     Jolteon  Electric       Non     0.8    24.5          0
135  136     Flareon      Fire       Non     0.9    25.0          0
136  137     Porygon    Normal       Non     0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal       Non     2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon       Non     1.8     3.3          0
147  148   Dragonair    Dragon       Non     4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic       Non     2.0   122.0          1

In [20]:
# fix inconsistent values
df["Type1"] = df["Type1"].replace({"Grass":"GRASS"})
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     GRASS    Poison     0.7     6.9          0
1      2     Ivysaur     GRASS    Poison     1.0    13.0          0
2      3    Venusaur     GRASS    Poison     2.0   100.0          0
3      4  Charmander      Fire       Non     0.6     8.5          0
4      5  Charmeleon      Fire       Non     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water       Non     0.5     9.0          0
7      8   Wartortle     Water       Non     1.0    22.5          0
8      9   Blastoise     Water       Non     1.6    85.5          0
9     10    Caterpie       Bug       Non     0.3     2.9          0
10    11     Metapod       Bug       Non     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal       Non     0.3     3.5          0
19    20    Raticate    Normal       Non     0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison       Non     2.0     6.9          0
23    24       Arbok    Poison       Non     3.5    65.0          0
24    25     Pikachu  Electric       Non     0.4     6.0          0
25    26      Raichu  Electric       Non     0.8    30.0          0
26    27   Sandshrew    Ground       Non     0.6    12.0          0
27    28   Sandslash    Ground       Non     1.0    29.5          0
28    29    Nidoran♀    Poison       Non     0.4     7.0          0
29    30    Nidorina    Poison       Non     0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison       Non     0.5     9.0          0
32    33    Nidorino    Poison       Non     0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy       Non     0.6     7.5          0
35    36    Clefable     Fairy       Non     1.3    40.0          0
36    37      Vulpix      Fire       Non     0.6     9.9          0
37    38   Ninetales      Fire       Non     1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     GRASS    Poison     0.5     5.4          0
43    44       Gloom     GRASS    Poison     0.8     8.6          0
44    45   Vileplume     GRASS    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground       Non     0.2     0.8          0
50    51     Dugtrio    Ground       Non     0.7    33.3          0
51    52      Meowth    Normal       Non     0.4     4.2          0
52    53     Persian    Normal       Non     1.0    32.0          0
53    54     Psyduck     Water       Non     0.8    19.6          0
54    55     Golduck     Water       Non     1.7    76.6          0
55    56      Mankey  Fighting       Non     0.5    28.0          0
56    57    Primeape  Fighting       Non     1.0    32.0          0
57    58   Growlithe      Fire       Non     0.7    19.0          0
58    59    Arcanine      Fire       Non     1.9   155.0          0
59    60     Poliwag     Water       Non     0.6    12.4          0
60    61   Poliwhirl     Water       Non     1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic       Non     0.9    19.5          0
63    64     Kadabra   Psychic       Non     1.3    56.5          0
64    65    Alakazam   Psychic       Non     1.5    48.0          0
65    66      Machop  Fighting       Non     0.8    19.5          0
66    67     Machoke  Fighting       Non     1.5    70.5          0
67    68     Machamp  Fighting       Non     1.6   130.0          0
68    69  Bellsprout     GRASS    Poison     0.7     4.0          0
69    70  Weepinbell     GRASS    Poison     1.0     6.4          0
70    71  Victreebel     GRASS    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire       Non     1.0    30.0          0
77    78    Rapidash      Fire       Non     1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water       Non     1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison       Non     0.9    30.0          0
88    89         Muk    Poison       Non     1.2    30.0          0
89    90    Shellder     Water       Non     0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic       Non     1.0    32.4          0
96    97       Hypno   Psychic       Non     1.6    75.6          0
97    98      Krabby     Water       Non     0.4     6.5          0
98    99     Kingler     Water       Non     1.3    60.0          0
99   100     Voltorb  Electric       Non     0.5    10.4          0
100  101   Electrode  Electric       Non     1.2    66.6          0
101  102   Exeggcute     GRASS   Psychic     0.4     2.5          0
102  103   Exeggutor     GRASS   Psychic     2.0   120.0          0
103  104      Cubone    Ground       Non     0.4     6.5          0
104  105     Marowak    Ground       Non     1.0    45.0          0
105  106   Hitmonlee  Fighting       Non     1.5    49.8          0
106  107  Hitmonchan  Fighting       Non     1.4    50.2          0
107  108   Lickitung    Normal       Non     1.2    65.5          0
108  109     Koffing    Poison       Non     0.6     1.0          0
109  110     Weezing    Poison       Non     1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal       Non     1.1    34.6          0
113  114     Tangela     GRASS       Non     1.0    35.0          0
114  115  Kangaskhan    Normal       Non     2.2    80.0          0
115  116      Horsea     Water       Non     0.4     8.0          0
116  117      Seadra     Water       Non     1.2    25.0          0
117  118     Goldeen     Water       Non     0.6    15.0          0
118  119     Seaking     Water       Non     1.3    39.0          0
119  120      Staryu     Water       Non     0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric       Non     1.1    30.0          0
125  126      Magmar      Fire       Non     1.3    44.5          0
126  127      Pinsir       Bug       Non     1.5    55.0          0
127  128      Tauros    Normal       Non     1.4    88.4          0
128  129    Magikarp     Water       Non     0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal       Non     0.3     4.0          0
132  133       Eevee    Normal       Non     0.3     6.5          0
133  134    Vaporeon     Water       Non     1.0    29.0          0
134  135     Jolteon  Electric       Non     0.8    24.5          0
135  136     Flareon      Fire       Non     0.9    25.0          0
136  137     Porygon    Normal       Non     0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal       Non     2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon       Non     1.8     3.3          0
147  148   Dragonair    Dragon       Non     4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic       Non     2.0   122.0          1

In [22]:
df["Type1"] = df["Type1"].replace({"Fire":"GRASS",
                                   "Water":"WATER"})
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     GRASS    Poison     0.7     6.9          0
1      2     Ivysaur     GRASS    Poison     1.0    13.0          0
2      3    Venusaur     GRASS    Poison     2.0   100.0          0
3      4  Charmander     GRASS       Non     0.6     8.5          0
4      5  Charmeleon     GRASS       Non     1.1    19.0          0
5      6   Charizard     GRASS    Flying     1.7    90.5          0
6      7    Squirtle     WATER       Non     0.5     9.0          0
7      8   Wartortle     WATER       Non     1.0    22.5          0
8      9   Blastoise     WATER       Non     1.6    85.5          0
9     10    Caterpie       Bug       Non     0.3     2.9          0
10    11     Metapod       Bug       Non     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal       Non     0.3     3.5          0
19    20    Raticate    Normal       Non     0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison       Non     2.0     6.9          0
23    24       Arbok    Poison       Non     3.5    65.0          0
24    25     Pikachu  Electric       Non     0.4     6.0          0
25    26      Raichu  Electric       Non     0.8    30.0          0
26    27   Sandshrew    Ground       Non     0.6    12.0          0
27    28   Sandslash    Ground       Non     1.0    29.5          0
28    29    Nidoran♀    Poison       Non     0.4     7.0          0
29    30    Nidorina    Poison       Non     0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison       Non     0.5     9.0          0
32    33    Nidorino    Poison       Non     0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy       Non     0.6     7.5          0
35    36    Clefable     Fairy       Non     1.3    40.0          0
36    37      Vulpix     GRASS       Non     0.6     9.9          0
37    38   Ninetales     GRASS       Non     1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     GRASS    Poison     0.5     5.4          0
43    44       Gloom     GRASS    Poison     0.8     8.6          0
44    45   Vileplume     GRASS    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground       Non     0.2     0.8          0
50    51     Dugtrio    Ground       Non     0.7    33.3          0
51    52      Meowth    Normal       Non     0.4     4.2          0
52    53     Persian    Normal       Non     1.0    32.0          0
53    54     Psyduck     WATER       Non     0.8    19.6          0
54    55     Golduck     WATER       Non     1.7    76.6          0
55    56      Mankey  Fighting       Non     0.5    28.0          0
56    57    Primeape  Fighting       Non     1.0    32.0          0
57    58   Growlithe     GRASS       Non     0.7    19.0          0
58    59    Arcanine     GRASS       Non     1.9   155.0          0
59    60     Poliwag     WATER       Non     0.6    12.4          0
60    61   Poliwhirl     WATER       Non     1.0    20.0          0
61    62   Poliwrath     WATER  Fighting     1.3    54.0          0
62    63        Abra   Psychic       Non     0.9    19.5          0
63    64     Kadabra   Psychic       Non     1.3    56.5          0
64    65    Alakazam   Psychic       Non     1.5    48.0          0
65    66      Machop  Fighting       Non     0.8    19.5          0
66    67     Machoke  Fighting       Non     1.5    70.5          0
67    68     Machamp  Fighting       Non     1.6   130.0          0
68    69  Bellsprout     GRASS    Poison     0.7     4.0          0
69    70  Weepinbell     GRASS    Poison     1.0     6.4          0
70    71  Victreebel     GRASS    Poison     1.7    15.5          0
71    72   Tentacool     WATER    Poison     0.9    45.5          0
72    73  Tentacruel     WATER    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta     GRASS       Non     1.0    30.0          0
77    78    Rapidash     GRASS       Non     1.7    95.0          0
78    79    Slowpoke     WATER   Psychic     1.2    36.0          0
79    80     Slowbro     WATER   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     WATER       Non     1.1    90.0          0
86    87     Dewgong     WATER       Ice     1.7   120.0          0
87    88      Grimer    Poison       Non     0.9    30.0          0
88    89         Muk    Poison       Non     1.2    30.0          0
89    90    Shellder     WATER       Non     0.3     4.0          0
90    91    Cloyster     WATER       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic       Non     1.0    32.4          0
96    97       Hypno   Psychic       Non     1.6    75.6          0
97    98      Krabby     WATER       Non     0.4     6.5          0
98    99     Kingler     WATER       Non     1.3    60.0          0
99   100     Voltorb  Electric       Non     0.5    10.4          0
100  101   Electrode  Electric       Non     1.2    66.6          0
101  102   Exeggcute     GRASS   Psychic     0.4     2.5          0
102  103   Exeggutor     GRASS   Psychic     2.0   120.0          0
103  104      Cubone    Ground       Non     0.4     6.5          0
104  105     Marowak    Ground       Non     1.0    45.0          0
105  106   Hitmonlee  Fighting       Non     1.5    49.8          0
106  107  Hitmonchan  Fighting       Non     1.4    50.2          0
107  108   Lickitung    Normal       Non     1.2    65.5          0
108  109     Koffing    Poison       Non     0.6     1.0          0
109  110     Weezing    Poison       Non     1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal       Non     1.1    34.6          0
113  114     Tangela     GRASS       Non     1.0    35.0          0
114  115  Kangaskhan    Normal       Non     2.2    80.0          0
115  116      Horsea     WATER       Non     0.4     8.0          0
116  117      Seadra     WATER       Non     1.2    25.0          0
117  118     Goldeen     WATER       Non     0.6    15.0          0
118  119     Seaking     WATER       Non     1.3    39.0          0
119  120      Staryu     WATER       Non     0.8    34.5          0
120  121     Starmie     WATER   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric       Non     1.1    30.0          0
125  126      Magmar     GRASS       Non     1.3    44.5          0
126  127      Pinsir       Bug       Non     1.5    55.0          0
127  128      Tauros    Normal       Non     1.4    88.4          0
128  129    Magikarp     WATER       Non     0.9    10.0          0
129  130    Gyarados     WATER    Flying     6.5   235.0          0
130  131      Lapras     WATER       Ice     2.5   220.0          0
131  132       Ditto    Normal       Non     0.3     4.0          0
132  133       Eevee    Normal       Non     0.3     6.5          0
133  134    Vaporeon     WATER       Non     1.0    29.0          0
134  135     Jolteon  Electric       Non     0.8    24.5          0
135  136     Flareon     GRASS       Non     0.9    25.0          0
136  137     Porygon    Normal       Non     0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal       Non     2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres     GRASS    Flying     2.0    60.0          1
146  147     Dratini    Dragon       Non     1.8     3.3          0
147  148   Dragonair    Dragon       Non     4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic       Non     2.0   122.0          1

In [23]:
# STANDARDIZE TEXT
df["Name"] = df["Name"].str.lower()
print(df)

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   bulbasaur    GRASS  Poison     0.7     6.9          0
1      2     ivysaur    GRASS  Poison     1.0    13.0          0
2      3    venusaur    GRASS  Poison     2.0   100.0          0
3      4  charmander    GRASS     Non     0.6     8.5          0
4      5  charmeleon    GRASS     Non     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     moltres    GRASS  Flying     2.0    60.0          1
146  147     dratini   Dragon     Non     1.8     3.3          0
147  148   dragonair   Dragon     Non     4.0    16.5          0
148  149   dragonite   Dragon  Flying     2.2   210.0          0
149  150      mewtwo  Psychic     Non     2.0   122.0          1

[150 rows x 7 columns]

In [24]:
# FIX DATATYPES
df["Legendary"] = df["Legendary"].astype(bool)
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   bulbasaur    GRASS  Poison     0.7     6.9      False
1      2     ivysaur    GRASS  Poison     1.0    13.0      False
2      3    venusaur    GRASS  Poison     2.0   100.0      False
3      4  charmander    GRASS     Non     0.6     8.5      False
4      5  charmeleon    GRASS     Non     1.1    19.0      False
..   ...         ...      ...     ...     ...     ...        ...
145  146     moltres    GRASS  Flying     2.0    60.0       True
146  147     dratini   Dragon     Non     1.8     3.3      False
147  148   dragonair   Dragon     Non     4.0    16.5      False
148  149   dragonite   Dragon  Flying     2.2   210.0      False
149  150      mewtwo  Psychic     Non     2.0   122.0       True

[150 rows x 7 columns]

In [25]:
# REMOVE DUPLICATES VALUES
df = df.drop_duplicates()
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   bulbasaur    GRASS  Poison     0.7     6.9      False
1      2     ivysaur    GRASS  Poison     1.0    13.0      False
2      3    venusaur    GRASS  Poison     2.0   100.0      False
3      4  charmander    GRASS     Non     0.6     8.5      False
4      5  charmeleon    GRASS     Non     1.1    19.0      False
..   ...         ...      ...     ...     ...     ...        ...
145  146     moltres    GRASS  Flying     2.0    60.0       True
146  147     dratini   Dragon     Non     1.8     3.3      False
147  148   dragonair   Dragon     Non     4.0    16.5      False
148  149   dragonite   Dragon  Flying     2.2   210.0      False
149  150      mewtwo  Psychic     Non     2.0   122.0       True

[150 rows x 7 columns]